// Test generated by RoostGPT for test roost-test using AI Type Open Source AI and AI Model meta-llama/Llama-2-13b-chat

package test

import (
	"fmt"
	"strconv"
	"testing"
)

func TestDigitalRootWithString(t *testing.T) {
	testCases := []struct {
		name     string
		input    int
		expected int
	}{
		{
			name:     "single digit",
			input:     5,
			expected: 5,
		},
		{
			name:     "two digits",
			input:    123,
			expected: 6,
		},
		{
			name:     "three digits",
			input:    456,
			expected: 9,
		},
		{
			name:     "negative number",
			input:    -789,
			expected: -9,
		},
	}

	for _, tc := range testCases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			result := DigitalRootWithString(tc.input)
			if result!= tc.expected {
				t.Errorf("got %v, expected %v", result, tc.expected)
			}
		})
	}
}

func TestDigitalRootWithString_edgeCases(t *testing.T) {
	cases := map[string]int{"": 0, "1": 1, "123": 6, "-123": -9}
	for input, expected := range cases {
		t.Run(input, func(t *testing.T) {
			result := DigitalRootWithString(input)
			if result!= expected {
				t.Errorf("got %v, expected %v", result, expected)
			}
		})
	}
}
